# =============================================================================
# Default Runner configuration
# =============================================================================

taskman:
    bin_dir: ~
