# -----------------------------------------------------------------------------
# List of dynamically-defined commands.
# -----------------------------------------------------------------------------
commands: []
